#!/bin/bash

## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##
##                                         ORION DESIGN                                        ##
## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##

## Cores
amarillo="\e[33m"
verde="\e[32m"
blanco="\e[97m"
beige="\e[93m"
rojo="\e[91m"
reset="\e[0m"

## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##
##                                         ORION DESIGN                                        ##
## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##

sudo apt update

sudo apt upgrade -y

## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##
##                                         ORION DESIGN                                        ##
## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##

nome_aviso(){

clear
echo ""
echo -e "$amarillo==================================================================================================$reset"
echo -e "$amarillo=                                                                                                 $amarillo=$reset"
echo -e "$amarillo=                     $blanco  █████╗     ██╗   ██╗    ██╗    ███████╗     ██████╗                $amarillo=$reset"
echo -e "$amarillo=                     $blanco ██╔══██╗    ██║   ██║    ██║    ██╔════╝    ██╔═══██╗               $amarillo=$reset"
echo -e "$amarillo=                     $blanco ███████║    ██║   ██║    ██║    ███████╗    ██║   ██║               $amarillo=$reset"
echo -e "$amarillo=                     $blanco ██╔══██║    ╚██╗ ██╔╝    ██║    ╚════██║    ██║   ██║               $amarillo=$reset"
echo -e "$amarillo=                     $blanco ██║  ██║     ╚████╔╝     ██║    ███████║    ╚██████╔╝               $amarillo=$reset"
echo -e "$amarillo=                     $blanco ╚═╝  ╚═╝      ╚═══╝      ╚═╝    ╚══════╝     ╚═════╝                $amarillo=$reset"
echo -e "$amarillo=                                                                                                 $amarillo=$reset"
echo -e "$amarillo==================================================================================================$reset"
echo ""
echo ""
}

nome_atualizadno(){
    clear
    echo ""
    echo -e "$amarillo==============================================================================================$reset"
    echo -e "$amarillo=                                                                                             $amarillo=$reset"
    echo -e "$amarillo=    $blanco              ██╗   ██╗██████╗ ███████╗  █████╗ ████████╗███████╗                 $amarillo=$reset"
    echo -e "$amarillo=    $blanco              ██║   ██║██╔══██╗██╔═══██╗██╔══██╗╚══██╔══╝██╔════╝                 $amarillo=$reset"
    echo -e "$amarillo=    $blanco              ██║   ██║██████╔╝██║   ██║███████║   ██║   █████╗                   $amarillo=$reset"
    echo -e "$amarillo=    $blanco              ██║   ██║██╔═══╝ ██║   ██║██╔══██║   ██║   ██╔══╝                   $amarillo=$reset"
    echo -e "$amarillo=    $blanco              ╚██████╔╝██║     ███████╔╝██║  ██║   ██║   ███████╗                 $amarillo=$reset"
    echo -e "$amarillo=    $blanco               ╚═════╝ ╚═╝      ╚═════╝ ╚═╝  ╚═╝   ╚═╝   ╚══════╝                 $amarillo=$reset"
    echo -e "$amarillo=                                                                                             $amarillo=$reset"
    echo -e "$amarillo==============================================================================================$reset"
    echo ""
    echo ""
}
nome_iniciando(){
    clear
    echo ""
    echo -e "$amarillo==================================================================================================$reset"
    echo -e "$amarillo=                                                                                                 $amarillo=$reset"
    echo -e "$amarillo=              $blanco ██╗███╗   ██╗██╗ ██████╗██╗ █████╗ ███╗   ██╗██████╗  ██████╗              $amarillo=$reset"
    echo -e "$amarillo=              $blanco ██║████╗  ██║██║██╔════╝██║██╔══██╗████╗  ██║██╔══██╗██╔═══██╗             $amarillo=$reset"
    echo -e "$amarillo=              $blanco ██║██╔██╗ ██║██║██║     ██║███████║██╔██╗ ██║██║  ██║██║   ██║             $amarillo=$reset"
    echo -e "$amarillo=              $blanco ██║██║╚██╗██║██║██║     ██║██╔══██║██║╚██╗██║██║  ██║██║   ██║             $amarillo=$reset"
    echo -e "$amarillo=              $blanco ██║██║ ╚████║██║╚██████╗██║██║  ██║██║ ╚████║██████╔╝╚██████╔╝             $amarillo=$reset"
    echo -e "$amarillo=              $blanco ╚═╝╚═╝  ╚═══╝╚═╝ ╚═════╝╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝              $amarillo=$reset"
    echo -e "$amarillo=                                              v. 2.7.0                                           $amarillo=$reset"
    echo -e "$amarillo==================================================================================================$reset"
    echo ""
    echo ""
}

nome_verificando(){
    clear
    echo ""
    echo -e "$amarillo========================================================================================================$reset"
    echo -e "$amarillo=                                                                                                       $amarillo=$reset"
    echo -e "$amarillo=       $blanco ██╗   ██╗███████╗██████╗ ██╗███████╗██╗ ██████╗ █████╗ ███╗   ██╗██████╗  ██████╗       $amarillo=$reset"
    echo -e "$amarillo=       $blanco ██║   ██║██╔════╝██╔══██╗██║██╔════╝██║██╔════╝██╔══██╗████╗  ██║██╔══██╗██╔═══██╗      $amarillo=$reset"
    echo -e "$amarillo=       $blanco ██║   ██║█████╗  ██████╔╝██║█████╗  ██║██║     ███████║██╔██╗ ██║██║  ██║██║   ██║      $amarillo=$reset"
    echo -e "$amarillo=       $blanco ╚██╗ ██╔╝██╔══╝  ██╔══██╗██║██╔══╝  ██║██║     ██╔══██║██║╚██╗██║██║  ██║██║   ██║      $amarillo=$reset"
    echo -e "$amarillo=       $blanco  ╚████╔╝ ███████╗██║  ██║██║██║     ██║╚██████╗██║  ██║██║ ╚████║██████╔╝╚██████╔╝      $amarillo=$reset"
    echo -e "$amarillo=       $blanco   ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═╝╚═╝     ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝       $amarillo=$reset"
    echo -e "$amarillo=                                                                                                       $amarillo=$reset"
    echo -e "$amarillo========================================================================================================$reset"
    echo ""
    echo ""
}
## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##
##                                         ORION DESIGN                                        ##
## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##

desc_ver(){
echo -e "                       Este script recomienda el uso de Ubuntu$amarillo 20.04$blanco.$reset"
echo ""
} 

## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##
##                                         ORION DESIGN                                        ##
## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##

clear
nome_verificando
echo "Espere mientras verificamos algunas informaciones"
sleep 1

# Verifica si se está usando Ubuntu 20.04
if ! grep -q 'Ubuntu 20.04' /etc/os-release; then
    nome_aviso
    desc_ver
    #echo "Este script recomienda el uso de Ubuntu 20.04."
    sleep 5
    clear
    nome_verificando
fi

# Verifica si el usuario es root
if [ "$(id -u)" -ne 0 ]; then
    echo "Este script necesita ser ejecutado como root. Ejecutando sudo su..."
    sudo su
fi

# Verifica se el usuario esta en el directorio /root/
if [ "$PWD" != "/root" ]; then
    echo "Cambiando el directorio /root/"
    cd /root || exit
fi

## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##
##                                         ORION DESIGN                                        ##
## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##


nome_iniciando 

## Realizando upgrade
sudo apt upgrade -y > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "1/14 - [ OK ]  - Realizando Actualización"
else
    echo "1/14 - [ OFF ] - Realizando Actualización"
fi

echo ""

## Instalando Sudo
apt install sudo -y > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "2/14 - [ OK ]  - Verificando/Instalando sudo"
else
    echo "2/14 - [ OFF ] - Verificando/Instalando sudo"
fi

echo ""

## Instalando apt-utils
sudo apt-get install -y apt-utils > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "3/14 - [ OK ]  - Verificando/Instalando apt-utils"
else
    echo "3/14 - [ OFF ] - Verificando/Instalando apt-utils"
fi

echo ""

## Instalando dialog
sudo apt-get install -y dialog > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "4/14 - [ OK ]  - Verificando/Instalando dialog"
else
    echo "4/14 - [ OFF ] - Verificando/Instalando dialog"
fi

echo ""

## Instalando jq
sudo apt-get install -y jq > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "5/14 - [ OK ]  - Verificando/Instalando jq 1/2"
else
    echo "5/14 - [ OFF ] - Verificando/Instalando jq 1/2"
fi

echo ""

## Instalando jq
sudo apt install jq -y > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "6/14 - [ OK ]  - Verificando/Instalando jq 2/2"
else
    echo "6/14 - [ OFF ] - Verificando/Instalando jq 2/2"
fi

echo ""

## Instalando apache2-utils
sudo apt install apache2-utils -y > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "7/14 - [ OK ]  - Verificando/Instalando apache2-utils 1/2"
else
    echo "7/14 - [ OFF ] - Verificando/Instalando apache2-utils1/2"
fi

echo ""

## Instalando apache2-utils
apt install apache2-utils -y > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "8/14 - [ OK ]  - Verificando/Instalando apache2-utils 2/2"
else
    echo "8/14 - [ OFF ] - Verificando/Instalando apache2-utils 2/2"
fi

echo ""

## Instalando git
apt install git -y > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "9/14 - [ OK ]  - Verificando/Instalando Git"
else
    echo "9/14 - [ OFF ] - Verificando/Instalando Git"
fi

echo ""

## Instalando python3
apt install python3 -y > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "10/14 - [ OK ]  - Verificando/Instalando python3"
else
    echo "10/14 - [ OFF ] - Verificando/Instalando python3"
fi

echo ""

## Realizando update
sudo apt update > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "11/14 - [ OK ]  - Realizando Actualizacion"
else
    echo "11/14 - [ OFF ] - Realizando Actualizacion"
fi

echo ""

## Realizando upgrade
sudo apt upgrade -y > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "12/14 - [ OK ]  - Realizando Actualizacion"
else
    echo "12/14 - [ OFF ] - Realizando Actualizacion"
fi

echo ""

## Instalando neofetch
apt install neofetch -y > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "13/14 - [ OK ]  - Verificando/Instalando neofetch"
else
    echo "13/14 - [ OFF ] - Verificando/Instalando neofetch"
fi

echo ""

# Verifica si el archivo SetupOrion ya existe
if [ -e "SetupOrion" ]; then
    echo ""
    rm SetupOrion
fi

curl -sSL https://raw.githubusercontent.com/oriondesign2015/SetupOrion/main/SetupOrion -o SetupOrion
if [ $? -eq 0 ]; then
    echo "14/14 - [ OK ]  - Descargando el script"
    # Modificar valores en el script
    sed -i 's/DEFAULT_ORGANIZATION_NAME=OrionDesign/DEFAULT_ORGANIZATION_NAME=Aplicki/g' SetupOrion
    sed -i 's/DEFAULT_PROJECT_NAME=SetupOrion/DEFAULT_PROJECT_NAME=Renov-PC/g' SetupOrion
    # Ejecutar el script modificado
    chmod +x SetupOrion
    ./SetupOrion
else
    echo "14/14 - [ OFF ] - Descargando el script"
    echo "Finalizando setup"
    sleep 5
fi


## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##
##                                         ORION DESIGN                                        ##
## // ## // ## // ## // ## // ## // ## // ## //## // ## // ## // ## // ## // ## // ## // ## // ##

sudo apt update
sudo apt upgrade -y

clear
rm SetupOrion